# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthentificatorAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

        # Add other firewall configurations as needed

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/dashboard/, roles: ROLE_ADMIN }
        - { path: ^/societe/, roles: ROLE_SOCIETE }
        - { path: ^/user/, roles: [ROLE_ADMIN] }
        - { path: ^/user/editUser, roles: [ROLE_USER] }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_SOCIETE]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

# Optional: Additional firewall configurations for different environments
# dev:
#     ...

# prod:
#     ...

# Add other environment-specific configurations as needed
